In [3]:
# import Librairies
import pandas as pd 
import matplotlib.pyplot as plt

# Data & Clean
df = pd.read_csv(r'C:\Users\PC\Documents\Learning_PYTHON\data_jobs.csv')
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 86.2 MB

In [5]:
df.loc [:10 , 'salary_rate':'salary_hour_avg']

   salary_rate  salary_year_avg  salary_hour_avg
0          NaN              NaN              NaN
1          NaN              NaN              NaN
2          NaN              NaN              NaN
3          NaN              NaN              NaN
4          NaN              NaN              NaN
5          NaN              NaN              NaN
6          NaN              NaN              NaN
7          NaN              NaN              NaN
8          NaN              NaN              NaN
9          NaN              NaN              NaN
10         NaN              NaN              NaN

In [ ]:
# Our job in this stage is to replace all the NAN salary values by median salary values , and Drop duplicate 

# Calculate the median
median_salary_hour = df['salary_hour_avg'].median()
median_salary_year = df['salary_year_avg'].median()

In [ ]:
# Fill the NaN values by the median using " fillna() "
df['salary_hour_avg'] = df['salary_hour_avg'].fillna(median_salary_hour)
df['salary_year_avg'] = df['salary_year_avg'].fillna(median_salary_year)

In [15]:
# Result
df_filled = df
df_filled.loc[:10 , 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

In [23]:
# Drop Duplicates , Using " .drop_duplicate "
df_unique = df_filled
df_unique = df_unique.drop_duplicates()

print ('Length of original df is :      ' , len(df_filled) )
print ('Lenght of drop duplicate is :   ' , len(df_unique))
print ( 'Rows dropped :                  ' , len(df_filled)-len(df_unique))

Length of original df is :       785741
Lenght of drop duplicate is :    785640
Rows dropped :                   101

In [25]:
# Now lets drop duplicates but with 2 column not the entire data 
df_unique_2 = df_unique.drop_duplicates (subset =['job_title' , 'company_name'])

print ('Length of original df is :      ' , len(df_unique) )
print ('Lenght of drop duplicate is :   ' , len(df_unique_2))
print ( 'Rows dropped :                  ' , len(df_unique)-len(df_unique_2))

Length of original df is :       785640
Lenght of drop duplicate is :    508042
Rows dropped :                   277598