In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\PC\Documents\PYTHON\data_jobs.csv")

#Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [ ]:
#this is the method Luka loves start with it Cuz its gives him general view on the data 
df.describe()

                  job_posted_date  salary_year_avg  salary_hour_avg
count                      785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860247    123286.274072        47.016598
min           2023-01-01 00:00:04     15000.000000         8.000000
25%           2023-03-20 10:05:48     90000.000000        27.500000
50%           2023-06-29 06:11:38    115000.000000        45.980000
75%           2023-09-27 01:01:16    150000.000000        61.159996
max           2023-12-31 23:59:58    960000.000000       391.000000
std                           NaN     48312.449482        21.890738

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 86.2 MB

In [ ]:
#The middle number in the column
df['salary_year_avg'].median()

np.float64(115000.0)

In [5]:
df['salary_year_avg'].min()

np.float64(15000.0)

In [9]:
#Gives you the index of the min value
min_salary = df['salary_year_avg'].idxmin()

In [10]:
#Shows you the informations about a row . or multiple rows
df.iloc[min_salary]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

In [12]:
#Shows you the values without repetion 
df['job_title_short'].unique()

<StringArray>
[     'Senior Data Engineer',              'Data Analyst',
             'Data Engineer',          'Business Analyst',
            'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst',            'Cloud Engineer',
     'Senior Data Scientist',         'Software Engineer']
Length: 10, dtype: str

In [13]:
df['job_title_short'].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

In [ ]:
#Calculate multiple categories by a method
df.groupby('job_title_short')[['salary_year_avg' , 'salary_hour_avg' ]].max()

                           salary_year_avg  salary_hour_avg
job_title_short
Business Analyst                  387460.0            132.5
Cloud Engineer                    280000.0             91.0
Data Analyst                      650000.0            391.0
Data Engineer                     525000.0            184.5
Data Scientist                    960000.0            237.5
Machine Learning Engineer         325000.0             87.5
Senior Data Analyst               425000.0            130.0
Senior Data Engineer              425000.0            170.0
Senior Data Scientist             890000.0            150.0
Software Engineer                 375000.0            102.5

In [37]:
#calculate  catefories by multiple calculations 
df.groupby('job_title_short')[['salary_year_avg' , 'salary_hour_avg' ]].agg(['min','max'])

                          salary_year_avg           salary_hour_avg
                                      min       max             min    max
job_title_short
Business Analyst                  16500.0  387460.0          10.835  132.5
Cloud Engineer                    42000.0  280000.0          18.500   91.0
Data Analyst                      25000.0  650000.0           8.000  391.0
Data Engineer                     15000.0  525000.0           8.000  184.5
Data Scientist                    27000.0  960000.0           8.000  237.5
Machine Learning Engineer         30000.0  325000.0          10.000   87.5
Senior Data Analyst               30000.0  425000.0          13.000  130.0
Senior Data Engineer              35000.0  425000.0          12.500  170.0
Senior Data Scientist             45000.0  890000.0          17.500  150.0
Software Engineer                 28000.0  375000.0          11.000  102.5