In [6]:
import pandas as pd
df = pd.read_csv(r"C:\Users\PC\Documents\PYTHON\data_jobs.csv")
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [10]:
df['job_location'].value_counts().head(20)

job_location
Anywhere                                                     69552
Singapore                                                    23415
Paris, France                                                12311
Bengaluru, Karnataka, India                                  11474
London, UK                                                   10564
Madrid, Spain                                                 9787
New York, NY                                                  8165
India                                                         7660
United States                                                 7454
Hong Kong                                                     7341
Lisbon, Portugal                                              7171
Atlanta, GA                                                   7148
Hyderabad, Telangana, India                                   6841
Dublin, Ireland                                               6559
Amsterdam, Netherlands                                        5981
Chicago, IL                                                   5543
United Kingdom                                                5317
Warsaw, Poland                                                5270
Dallas, TX                                                    5182
Kuala Lumpur, Federal Territory of Kuala Lumpur, Malaysia     5072
Name: count, dtype: int64

In [ ]:
#is morocoo in the data ? 
df['job_location'].isin(['Morocco']).any()

np.True_

In [ ]:
#show the anywhere data
Anywhere_jobs = df[ df['job_location'] == "Anywhere"]
Anywhere_jobs = Anywhere_jobs [ Anywhere_jobs['salary_year_avg'].notna()]
Anywhere_jobs

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
116,Data Scientist,Data Scientist,Anywhere,via LinkedIn,Full-time,True,"Texas, United States",2023-10-04 13:04:23,False,False,United States,year,114000.0,NaN,4 Corner Resources,"['r', 'python', 'sql', 't-sql', 'hadoop', 'spa...","{'analyst_tools': ['tableau'], 'libraries': ['..."
571,Data Engineer,Data Engineer ETL lnformatica API SQL Engineer...,Anywhere,via Robert Half,Full-time,True,"California, United States",2023-07-20 13:07:40,True,False,United States,year,110000.0,NaN,Robert Half,"['sql', 'java', 'python', 'azure', 'aws', 'sno...","{'cloud': ['azure', 'aws', 'snowflake'], 'prog..."
773,Data Engineer,Principal Data Engineer,Anywhere,via Indeed,Full-time,True,"Texas, United States",2023-05-17 13:22:20,True,False,United States,year,180000.0,NaN,CyberCoders,"['sql', 'python', 'aws', 'snowflake', 'spark',...","{'analyst_tools': ['tableau', 'microstrategy']..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
779816,Senior Data Scientist,Senior Data Scientist (Remote),Anywhere,via Built In,Full-time,True,Sudan,2023-06-13 06:32:30,False,True,Sudan,year,166500.0,NaN,Billtrust,"['sql', 'python', 'jupyter', 'pytorch', 'tenso...","{'libraries': ['jupyter', 'pytorch', 'tensorfl..."
780443,Data Scientist,Staff Data Scientist (Remote),Anywhere,via Built In,Full-time,True,"Illinois, United States",2023-05-04 05:04:56,False,True,United States,year,164500.0,NaN,Drata,"['sql', 'tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi'], 'pr..."
781466,Senior Data Scientist,"Senior Data Scientist (San Francisco, CA or Re...",Anywhere,via Built In San Francisco,Full-time,True,"California, United States",2023-09-21 06:02:34,False,True,United States,year,213172.5,NaN,SoFi,"['sql', 'vba', 'excel', 'flow']","{'analyst_tools': ['excel'], 'other': ['flow']..."
782562,Senior Data Engineer,Senior Data Science Engineer,Anywhere,via Motion Recruitment,Full-time,True,Georgia,2023-05-16 07:26:57,False,False,United States,year,182500.0,NaN,Motion Recruitment,"['python', 'gcp']","{'cloud': ['gcp'], 'programming': ['python']}"
783761,Senior Data Engineer,Senior Data Engineer,Anywhere,via LinkedIn,Full-time,True,"Texas, United States",2023-01-04 15:37:16,False,False,United States,year,130000.0,NaN,Elsdon Consulting ltd,"['azure', 'power bi']","{'analyst_tools': ['power bi'], 'cloud': ['azu..."

In [32]:
Anywhere_jobs.groupby("job_title_short")['salary_year_avg'].agg (['median' , 'min' , 'max', "count" ]).sort_values(by="median" , ascending=False)

                             median      min       max  count
job_title_short
Senior Data Scientist      160000.0  45000.0  475000.0    337
Senior Data Engineer       145000.0  35000.0  240000.0    283
Cloud Engineer             140000.0  90000.0  204000.0      9
Data Scientist             136000.0  30750.0  550000.0    949
Data Engineer              130000.0  20000.0  325000.0    751
Machine Learning Engineer  127500.0  32500.0  325000.0     40
Software Engineer          125000.0  28000.0  225000.0     63
Senior Data Analyst        105000.0  43031.0  185000.0    160
Business Analyst            90000.0  16500.0  220000.0     77
Data Analyst                86750.0  25000.0  650000.0    610