In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\PC\Documents\PYTHON\store_analytics.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1000 non-null   int64
 1   product_category  1000 non-null   str
 2   price             1000 non-null   float64
 3   customer_rating   850 non-null    float64
 4   shipping_status   1000 non-null   str
 5   order_date        1000 non-null   str
dtypes: float64(2), int64(1), str(3)
memory usage: 47.0 KB

In [2]:
df.describe()

          order_id        price  customer_rating
count  1000.000000  1000.000000       850.000000
mean   1500.500000   256.890810         3.518824
std     288.819436   285.024609         1.333716
min    1001.000000    12.210000         1.000000
25%    1250.750000    75.942500         3.000000
50%    1500.500000   132.965000         4.000000
75%    1750.250000   334.170000         5.000000
max    2000.000000  1198.100000         5.000000

In [3]:
df['order_date'] = pd.to_datetime(df.order_date)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1000 non-null   int64
 1   product_category  1000 non-null   str
 2   price             1000 non-null   float64
 3   customer_rating   850 non-null    float64
 4   shipping_status   1000 non-null   str
 5   order_date        1000 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(2)
memory usage: 47.0 KB

In [4]:
df['price'].isin(['NAN']).any()

np.False_

In [5]:
df['customer_rating'].count()

np.int64(850)

In [6]:
df.groupby('product_category')['customer_rating'].agg(['mean' , 'median', 'min' , 'max']).sort_values('mean')

                      mean  median  min  max
product_category
Home              3.395062     4.0  1.0  5.0
Clothing          3.503333     4.0  1.0  5.0
Electronics       3.549296     4.0  1.0  5.0
Beauty            3.622857     4.0  1.0  5.0

In [7]:
df['shipping_status'].unique()

<StringArray>
['Pending', 'Cancelled', 'Delivered']
Length: 3, dtype: str

In [8]:
df.groupby ('shipping_status')['price'].sum().sort_values()

shipping_status
Cancelled     24245.49
Pending       36005.46
Delivered    196639.86
Name: price, dtype: float64

In [9]:
#answer question 4
df = df.sort_values('order_date')
df['cumulative_sales'] = df['price'].cumsum()
df[['order_date' , 'cumulative_sales']]

    order_date  cumulative_sales
943 2026-03-01            144.46
601 2026-03-01            203.12
457 2026-03-01           1031.11
57  2026-03-01           1100.37
191 2026-03-01           1220.98
..         ...               ...
99  2026-06-23         256170.29
157 2026-06-23         256613.11
689 2026-06-24         256731.36
939 2026-06-24         256869.98
866 2026-06-24         256890.81

[1000 rows x 2 columns]

In [10]:
#question 5
df['month'] = df.order_date.dt.month
df['month'].value_counts().sort_values(ascending=False)

month
5    276
3    270
4    265
6    189
Name: count, dtype: int64

In [19]:
home =df [ df['product_category'] == 'Home']
home.info()

<class 'pandas.DataFrame'>
Index: 188 entries, 238 to 157
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          188 non-null    int64
 1   product_category  188 non-null    str
 2   price             188 non-null    float64
 3   customer_rating   162 non-null    float64
 4   shipping_status   188 non-null    str
 5   order_date        188 non-null    datetime64[us]
 6   cumulative_sales  188 non-null    float64
 7   month             188 non-null    int32
dtypes: datetime64[us](1), float64(3), int32(1), int64(1), str(2)
memory usage: 12.5 KB

In [20]:
home.describe()

,order_id,price,customer_rating,order_date,cumulative_sales,month
count,188.000000,188.000000,162.000000,188,188.000000,188.000000
mean,1484.691489,268.420372,3.395062,2026-04-25 21:19:08.936170,122706.196702,4.351064
min,1003.000000,22.760000,1.000000,2026-03-01 00:00:00,1705.710000,3.000000
25%,1234.750000,150.582500,2.000000,2026-03-29 00:00:00,64945.812500,3.000000
50%,1449.500000,269.325000,4.000000,2026-04-26 00:00:00,121417.230000,4.000000
75%,1744.750000,387.905000,5.000000,2026-05-21 12:00:00,176211.222500,5.000000
max,1992.000000,498.410000,5.000000,2026-06-23 00:00:00,256613.110000,6.000000
std,286.092933,137.003613,1.371213,NaN,70181.292490,1.051685

In [23]:
home[ home['shipping_status'] == "Cancelled"].count()

order_id            20
product_category    20
price               20
customer_rating     14
shipping_status     20
order_date          20
cumulative_sales    20
month               20
dtype: int64

In [25]:
home [ home['shipping_status'] == "Pending"].count()

order_id            32
product_category    32
price               32
customer_rating     28
shipping_status     32
order_date          32
cumulative_sales    32
month               32
dtype: int64

In [27]:
home.sort_values(by='order_date')
home['price'].cumsum()

238      484.73
658      695.28
296      795.67
267     1046.04
780     1084.48
         ...
331    49241.27
114    49545.88
839    49673.70
337    50020.21
157    50463.03
Name: price, Length: 188, dtype: float64

In [37]:
#see the pending , cancelled , delevered sales for each month ( comparation )
result = home.groupby(['month' , 'shipping_status'])['price'].count()
result

month  shipping_status
3      Cancelled           6
       Delivered          37
       Pending             7
4      Cancelled           8
       Delivered          36
       Pending            10
5      Cancelled           3
       Delivered          41
       Pending             8
6      Cancelled           3
       Delivered          22
       Pending             7
Name: price, dtype: int64

In [39]:
sales_categories = df.groupby( ['product_category'])['price'].count().sort_values()
sales_categories

product_category
Home           188
Beauty         199
Electronics    248
Clothing       365
Name: price, dtype: int64

In [44]:
Total_sales = sales_categories.sum()
Percentage_sales = []
for x in sales_categories :
    result = (x/Total_sales)*100
    Percentage_sales.append(result)

Percentage_sales

[np.float64(18.8),
 np.float64(19.900000000000002),
 np.float64(24.8),
 np.float64(36.5)]